[2025-01-31T00:00:01.405+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-31T00:00:01.426+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: manage_airflow_roles.get_owners manual__2025-01-30T23:57:22.460856+00:00 [queued]>
[2025-01-31T00:00:01.436+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: manage_airflow_roles.get_owners manual__2025-01-30T23:57:22.460856+00:00 [queued]>
[2025-01-31T00:00:01.437+0000] {taskinstance.py:2866} INFO - Starting attempt 2 of 2
[2025-01-31T00:00:01.452+0000] {taskinstance.py:2889} INFO - Executing <Task(_PythonDecoratedOperator): get_owners> on 2025-01-30 23:57:22.460856+00:00
[2025-01-31T00:00:01.458+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=662) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-31T00:00:01.460+0000] {standard_task_runner.py:72} INFO - Started process 669 to run task
[2025-01-31T00:00:01.460+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'manage_***_roles', 'get_owners', 'manual__2025-01-30T23:57:22.460856+00:00', '--job-id', '76', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpf7o1gz6g']
[2025-01-31T00:00:01.461+0000] {standard_task_runner.py:105} INFO - Job 76: Subtask get_owners
[2025-01-31T00:00:01.506+0000] {task_command.py:467} INFO - Running <TaskInstance: manage_airflow_roles.get_owners manual__2025-01-30T23:57:22.460856+00:00 [running]> on host 512f7139f01a
[2025-01-31T00:00:01.603+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='data-team' AIRFLOW_CTX_DAG_ID='manage_***_roles' AIRFLOW_CTX_TASK_ID='get_owners' AIRFLOW_CTX_EXECUTION_DATE='2025-01-30T23:57:22.460856+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-30T23:57:22.460856+00:00'
[2025-01-31T00:00:01.604+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-31T00:00:01.607+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/***/dags
[2025-01-31T00:00:01.620+0000] {python.py:240} INFO - Done. Returned value was: ['data-team']
[2025-01-31T00:00:01.643+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-31T00:00:01.643+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=manage_***_roles, task_id=get_owners, run_id=manual__2025-01-30T23:57:22.460856+00:00, execution_date=20250130T235722, start_date=20250131T000001, end_date=20250131T000001
[2025-01-31T00:00:01.674+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-31T00:00:01.700+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-31T00:00:01.702+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
