[2025-02-01T00:32:07.018+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-01T00:32:07.040+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: manage_airflow_roles.get_owners manual__2025-02-01T00:32:05.658092+00:00 [queued]>
[2025-02-01T00:32:07.057+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: manage_airflow_roles.get_owners manual__2025-02-01T00:32:05.658092+00:00 [queued]>
[2025-02-01T00:32:07.058+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-02-01T00:32:07.089+0000] {taskinstance.py:2889} INFO - Executing <Task(_PythonDecoratedOperator): get_owners> on 2025-02-01 00:32:05.658092+00:00
[2025-02-01T00:32:07.096+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=3992) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-01T00:32:07.098+0000] {standard_task_runner.py:72} INFO - Started process 3995 to run task
[2025-02-01T00:32:07.100+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'manage_***_roles', 'get_owners', 'manual__2025-02-01T00:32:05.658092+00:00', '--job-id', '121', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpi1zt8g4c']
[2025-02-01T00:32:07.101+0000] {standard_task_runner.py:105} INFO - Job 121: Subtask get_owners
[2025-02-01T00:32:07.159+0000] {task_command.py:467} INFO - Running <TaskInstance: manage_airflow_roles.get_owners manual__2025-02-01T00:32:05.658092+00:00 [running]> on host dab0f5b0cfba
[2025-02-01T00:32:07.334+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='data-team' AIRFLOW_CTX_DAG_ID='manage_***_roles' AIRFLOW_CTX_TASK_ID='get_owners' AIRFLOW_CTX_EXECUTION_DATE='2025-02-01T00:32:05.658092+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-01T00:32:05.658092+00:00'
[2025-02-01T00:32:07.335+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-01T00:32:07.337+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/***/dags
[2025-02-01T00:32:07.351+0000] {python.py:240} INFO - Done. Returned value was: ['data-team']
[2025-02-01T00:32:07.373+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-01T00:32:07.373+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=manage_***_roles, task_id=get_owners, run_id=manual__2025-02-01T00:32:05.658092+00:00, execution_date=20250201T003205, start_date=20250201T003207, end_date=20250201T003207
[2025-02-01T00:32:07.395+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-01T00:32:07.418+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-01T00:32:07.420+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
