[2025-01-31T23:52:41.435+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-31T23:52:41.466+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: manage_airflow_roles.get_dags_by_owner manual__2025-01-30T23:57:22.460856+00:00 [queued]>
[2025-01-31T23:52:41.488+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: manage_airflow_roles.get_dags_by_owner manual__2025-01-30T23:57:22.460856+00:00 [queued]>
[2025-01-31T23:52:41.489+0000] {taskinstance.py:2866} INFO - Starting attempt 3 of 3
[2025-01-31T23:52:41.511+0000] {taskinstance.py:2889} INFO - Executing <Task(_PythonDecoratedOperator): get_dags_by_owner> on 2025-01-30 23:57:22.460856+00:00
[2025-01-31T23:52:41.520+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=96) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-31T23:52:41.522+0000] {standard_task_runner.py:72} INFO - Started process 101 to run task
[2025-01-31T23:52:41.524+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'manage_***_roles', 'get_dags_by_owner', 'manual__2025-01-30T23:57:22.460856+00:00', '--job-id', '85', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpga3q12zk']
[2025-01-31T23:52:41.526+0000] {standard_task_runner.py:105} INFO - Job 85: Subtask get_dags_by_owner
[2025-01-31T23:52:41.592+0000] {task_command.py:467} INFO - Running <TaskInstance: manage_airflow_roles.get_dags_by_owner manual__2025-01-30T23:57:22.460856+00:00 [running]> on host dab0f5b0cfba
[2025-01-31T23:52:41.768+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='data-team' AIRFLOW_CTX_DAG_ID='manage_***_roles' AIRFLOW_CTX_TASK_ID='get_dags_by_owner' AIRFLOW_CTX_EXECUTION_DATE='2025-01-30T23:57:22.460856+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-30T23:57:22.460856+00:00'
[2025-01-31T23:52:41.770+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-31T23:52:41.773+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/***/dags
[2025-01-31T23:52:41.787+0000] {python.py:240} INFO - Done. Returned value was: {'data-team': ['hello_world_dag', 'manage_***_roles']}
[2025-01-31T23:52:41.812+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-31T23:52:41.813+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=manage_***_roles, task_id=get_dags_by_owner, run_id=manual__2025-01-30T23:57:22.460856+00:00, execution_date=20250130T235722, start_date=20250131T235241, end_date=20250131T235241
[2025-01-31T23:52:41.859+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-31T23:52:41.872+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
