[2025-02-14T23:07:39.786+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-14T23:07:39.829+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: manage_airflow_roles.add_users_to_roles manual__2025-02-14T23:05:21.937919+00:00 [queued]>
[2025-02-14T23:07:39.853+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: manage_airflow_roles.add_users_to_roles manual__2025-02-14T23:05:21.937919+00:00 [queued]>
[2025-02-14T23:07:39.854+0000] {taskinstance.py:2866} INFO - Starting attempt 3 of 3
[2025-02-14T23:07:39.884+0000] {taskinstance.py:2889} INFO - Executing <Task(_PythonDecoratedOperator): add_users_to_roles> on 2025-02-14 23:05:21.937919+00:00
[2025-02-14T23:07:39.893+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1323) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-14T23:07:39.896+0000] {standard_task_runner.py:72} INFO - Started process 1324 to run task
[2025-02-14T23:07:39.897+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'manage_***_roles', 'add_users_to_roles', 'manual__2025-02-14T23:05:21.937919+00:00', '--job-id', '355', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpjnhdoimz']
[2025-02-14T23:07:39.899+0000] {standard_task_runner.py:105} INFO - Job 355: Subtask add_users_to_roles
[2025-02-14T23:07:39.974+0000] {task_command.py:467} INFO - Running <TaskInstance: manage_airflow_roles.add_users_to_roles manual__2025-02-14T23:05:21.937919+00:00 [running]> on host 71404c6b5320
[2025-02-14T23:07:40.161+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='data-team' AIRFLOW_CTX_DAG_ID='manage_***_roles' AIRFLOW_CTX_TASK_ID='add_users_to_roles' AIRFLOW_CTX_EXECUTION_DATE='2025-02-14T23:05:21.937919+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-14T23:05:21.937919+00:00'
[2025-02-14T23:07:40.162+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-14T23:07:40.166+0000] {logging_mixin.py:190} INFO - {'roles': {'data-team': ['teste-user@gmail.com']}}
[2025-02-14T23:07:40.167+0000] {logging_mixin.py:190} INFO - <class 'dict'>
[2025-02-14T23:07:40.167+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-14T23:07:40.189+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-14T23:07:40.190+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=manage_***_roles, task_id=add_users_to_roles, run_id=manual__2025-02-14T23:05:21.937919+00:00, execution_date=20250214T230521, start_date=20250214T230739, end_date=20250214T230740
[2025-02-14T23:07:40.233+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-14T23:07:40.270+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-14T23:07:40.273+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
