[2025-02-10T23:49:54.427+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-10T23:49:54.472+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: manage_airflow_roles.assign_generic_permissions_roles scheduled__2025-02-03T10:00:00+00:00 [queued]>
[2025-02-10T23:49:54.500+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: manage_airflow_roles.assign_generic_permissions_roles scheduled__2025-02-03T10:00:00+00:00 [queued]>
[2025-02-10T23:49:54.501+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-02-10T23:49:54.550+0000] {taskinstance.py:2889} INFO - Executing <Task(_PythonDecoratedOperator): assign_generic_permissions_roles> on 2025-02-03 10:00:00+00:00
[2025-02-10T23:49:54.563+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=191) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-10T23:49:54.568+0000] {standard_task_runner.py:72} INFO - Started process 195 to run task
[2025-02-10T23:49:54.572+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'manage_***_roles', 'assign_generic_permissions_roles', 'scheduled__2025-02-03T10:00:00+00:00', '--job-id', '142', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpgnjqfd71']
[2025-02-10T23:49:54.576+0000] {standard_task_runner.py:105} INFO - Job 142: Subtask assign_generic_permissions_roles
[2025-02-10T23:49:54.646+0000] {task_command.py:467} INFO - Running <TaskInstance: manage_airflow_roles.assign_generic_permissions_roles scheduled__2025-02-03T10:00:00+00:00 [running]> on host 9c5f21acce5a
[2025-02-10T23:49:54.780+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='data-team' AIRFLOW_CTX_DAG_ID='manage_***_roles' AIRFLOW_CTX_TASK_ID='assign_generic_permissions_roles' AIRFLOW_CTX_EXECUTION_DATE='2025-02-03T10:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-03T10:00:00+00:00'
[2025-02-10T23:49:54.781+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-10T23:49:58.106+0000] {dag.py:161} INFO - Assigning DAG Runs permissions to data-team
[2025-02-10T23:50:00.779+0000] {dag.py:161} INFO - Assigning DAG Runs permissions to data-team
[2025-02-10T23:50:03.880+0000] {dag.py:161} INFO - Assigning DAG Runs permissions to data-team
[2025-02-10T23:50:07.046+0000] {dag.py:161} INFO - Assigning DAG Runs permissions to data-team
[2025-02-10T23:50:09.993+0000] {dag.py:161} INFO - Assigning DAG Runs permissions to data-team
[2025-02-10T23:50:12.848+0000] {dag.py:161} INFO - Assigning DAG Runs permissions to data-team
[2025-02-10T23:50:15.922+0000] {dag.py:161} INFO - Assigning DAG Runs permissions to data-team
[2025-02-10T23:50:18.776+0000] {dag.py:161} INFO - Assigning DAG Runs permissions to data-team
[2025-02-10T23:50:21.562+0000] {dag.py:161} INFO - Assigning DAG Runs permissions to data-team
[2025-02-10T23:50:24.281+0000] {dag.py:161} INFO - Assigning DAG Runs permissions to data-team
[2025-02-10T23:50:27.190+0000] {dag.py:161} INFO - Assigning DAG Runs permissions to data-team
[2025-02-10T23:50:30.243+0000] {dag.py:161} INFO - Assigning DAG Runs permissions to data-team
[2025-02-10T23:50:33.459+0000] {dag.py:161} INFO - Assigning DAG Runs permissions to data-team
[2025-02-10T23:50:36.095+0000] {dag.py:161} INFO - Assigning DAG Runs permissions to data-team
[2025-02-10T23:50:38.826+0000] {dag.py:161} INFO - Assigning DAG Runs permissions to data-team
[2025-02-10T23:50:41.523+0000] {dag.py:161} INFO - Assigning DAG Runs permissions to data-team
[2025-02-10T23:50:45.238+0000] {dag.py:161} INFO - Assigning DAG Runs permissions to data-team
[2025-02-10T23:50:48.373+0000] {dag.py:161} INFO - Assigning DAG Runs permissions to data-team
[2025-02-10T23:50:51.899+0000] {dag.py:161} INFO - Assigning DAG Runs permissions to data-team
[2025-02-10T23:50:55.154+0000] {dag.py:161} INFO - Assigning DAG Runs permissions to data-team
[2025-02-10T23:50:58.086+0000] {dag.py:161} INFO - Assigning DAG Runs permissions to data-team
[2025-02-10T23:51:01.045+0000] {dag.py:161} INFO - Assigning DAG Runs permissions to data-team
[2025-02-10T23:51:04.088+0000] {dag.py:161} INFO - Assigning DAG Runs permissions to data-team
[2025-02-10T23:51:07.033+0000] {dag.py:161} INFO - Assigning DAG Runs permissions to data-team
[2025-02-10T23:51:09.986+0000] {dag.py:161} INFO - Assigning DAG Runs permissions to data-team
[2025-02-10T23:51:13.122+0000] {dag.py:161} INFO - Assigning DAG Runs permissions to data-team
[2025-02-10T23:51:15.309+0000] {local_task_job_runner.py:346} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2025-02-10T23:51:15.310+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-02-10T23:51:15.311+0000] {process_utils.py:132} INFO - Sending 15 to group 195. PIDs of all processes in the group: [930, 195]
[2025-02-10T23:51:15.312+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 195
[2025-02-10T23:51:15.312+0000] {taskinstance.py:3093} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-02-10T23:51:15.319+0000] {dag.py:163} INFO - Error assigning DAG Runs permissions to data-team
[2025-02-10T23:51:15.325+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=930, status='terminated', started='23:51:12') (930) terminated with exit code None
[2025-02-10T23:51:19.576+0000] {dag.py:161} INFO - Assigning DAG Runs permissions to data-team
[2025-02-10T23:51:23.717+0000] {dag.py:161} INFO - Assigning DAG Runs permissions to data-team
[2025-02-10T23:51:27.791+0000] {dag.py:161} INFO - Assigning DAG Runs permissions to data-team
[2025-02-10T23:51:31.374+0000] {dag.py:161} INFO - Assigning DAG Runs permissions to data-team
[2025-02-10T23:51:36.094+0000] {dag.py:161} INFO - Assigning DAG Runs permissions to data-team
[2025-02-10T23:51:40.700+0000] {dag.py:161} INFO - Assigning DAG Runs permissions to data-team
[2025-02-10T23:51:43.858+0000] {dag.py:161} INFO - Assigning DAG Runs permissions to data-team
[2025-02-10T23:51:47.495+0000] {dag.py:161} INFO - Assigning DAG Runs permissions to data-team
[2025-02-10T23:51:52.584+0000] {dag.py:161} INFO - Assigning DAG Runs permissions to data-team
[2025-02-10T23:51:57.229+0000] {dag.py:161} INFO - Assigning DAG Runs permissions to data-team
[2025-02-10T23:52:01.637+0000] {dag.py:161} INFO - Assigning DAG Runs permissions to data-team
[2025-02-10T23:52:05.216+0000] {dag.py:161} INFO - Assigning DAG Runs permissions to data-team
[2025-02-10T23:52:08.301+0000] {dag.py:161} INFO - Assigning DAG Runs permissions to data-team
[2025-02-10T23:52:11.359+0000] {dag.py:161} INFO - Assigning DAG Runs permissions to data-team
[2025-02-10T23:52:14.484+0000] {dag.py:161} INFO - Assigning DAG Runs permissions to data-team
[2025-02-10T23:52:15.343+0000] {process_utils.py:150} WARNING - process psutil.Process(pid=195, name='airflow task ru', status='sleeping', started='23:49:53') did not respond to SIGTERM. Trying SIGKILL
[2025-02-10T23:52:15.344+0000] {process_utils.py:87} INFO - Sending the signal 9 to group 195
[2025-02-10T23:52:15.353+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=195, name='airflow task ru', status='terminated', exitcode=<Negsignal.SIGKILL: -9>, started='23:49:53') (195) terminated with exit code -9
[2025-02-10T23:52:15.353+0000] {standard_task_runner.py:190} ERROR - ('Job 142 was killed before it finished (likely due to running out of memory)', 'For more information, see https://***.apache.org/docs/apache-***/stable/troubleshooting.html#LocalTaskJob-killed')
